language: php
php:
#  - '5.6' for now test travis only on 7.0 because there is problem with phantomJS on 5.6
  - '7.0'

before_install:
  - wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
  - sudo mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/phantomjs/bin/phantomjs

before_script:
    - sudo apt-get update
    - composer install --dev --prefer-dist
    - chmod -R 777 var/cache var/logs
    - sudo apt-get install xvfb
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - phantomjs --webdriver=8643 &
    - sleep 5

script:
    - bin/console --no-interaction cache:clear --env=test
    - bin/console --no-interaction cache:warmup --env=test
    - bin/console doctrine:schema:update --force --env=test
    - bin/console --no-interaction doctrine:fixtures:load --env=test
    - chmod -R 777 var/cache var/logs
    - bin/console server:start
    - vendor/bin/behat
    - bin/console server:stop
notifications:
  email:
    on_failure: always
