language: php
php:
  - '5.6'

before_script:
    - sudo apt-get update
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    # enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    # configure apache virtual hosts
    - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
    - sudo sed -i -e "/DocumentRoot/i\ServerName shop.dev" /etc/apache2/sites-available/default
    - echo "127.0.0.1 shop.dev" | sudo tee -a /etc/hosts
    - sudo service apache2 restart
    - composer install --dev --prefer-dist
    - chmod -R 777 var/cache var/logs
    - sudo apt-get install xvfb
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - "wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar"
    - "DISPLAY=:10 xvfb-run java -jar selenium-server-standalone-2.45.0.jar &"
    - sleep 5
script:
    - bin/console --no-interaction cache:clear --env=test
    - bin/console --no-interaction cache:warmup --env=test
    - bin/console doctrine:schema:update --force --env=test
    - chmod -R 777 var/cache var/logs
    - vendor/bin/behat