imports:
    - { resource: config_dev.yml }
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
#    profiler:
#        collect: false
#
#web_profiler:
#    toolbar: false
#    intercept_redirects: false
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: pdo_sqlite
        path: '%kernel.cache_dir%/behat.db'
        charset: UTF8