app:
    resource: "@AppBundle/Controller/"
    type:     annotation
admin:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/products
        permanent: true