# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    providers:
        database_users:
            entity: { class: AppBundle:User, property: username }
    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: security_login
                check_path: security_login
            logout:
                path: security_logout
            guard:
                authenticators:
                    - app.form_login_authenticator

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/checkout, role: ROLE_USER }
