services:
    user.util:
        class: AppBundle\Util\UserUtil
        autowire: true

    shopping_cart:
        class: AppBundle\Service\ShoppingCart
        autowire: true

    stripe.client:
        class: AppBundle\Stripe\StripeClient
        autowire: true
        arguments: ['%stripe_secret_key%']

    subscription_helper:
        class: AppBundle\Stripe\SubscriptionHelper
        autowire: true