services:
    user.util:
        class: AppBundle\Util\UserUtil
        autowire: true
    shopping_cart:
        class: AppBundle\Service\ShoppingCart
        autowire: true
    stripe:
        class: AppBundle\Service\Stripe
        autowire: true
        arguments: ['%stripe_secret_key%',"@=service('security.token_storage').getToken().getUser()"]